'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');

const { parseVideoUrl } = require('../lib/video-learning/video-sources');
const { buildLesson } = require('../lib/video-learning/lesson-extractor');
const { proposeTasks } = require('../lib/video-learning/task-proposal');
const {
  renderLessonMarkdown,
  renderIndexTable,
  applyIndexBlock,
  buildIndexEntry,
  mergeIndex,
  saveLesson,
  INDEX_START,
  INDEX_END
} = require('../lib/video-learning/lesson-store');
const { parseInbox, removeProcessed } = require('../lib/video-learning/intake-queue');

const SOURCE = parseVideoUrl('https://youtu.be/dQw4w9WgXcQ');

function makeTranscript(script) {
  const words = script.split(/\s+/).filter(Boolean);
  const segments = [];
  for (let i = 0; i < words.length; i += 4) {
    segments.push({ start: (i / 4) * 2, duration: 2, text: words.slice(i, i + 4).join(' ') });
  }
  return { segments, text: script, language: 'en', autoGenerated: false };
}

const CLEAN_SCRIPT = [
  'The biggest mistake people make is launching twelve creatives at once.',
  'Step one, pick a single winning hook and hold it for two weeks.',
  'Never change the budget and the creative in the same week.',
  'We held the CPM at $40 for 90 days and it returned 3x.',
  'I recommend testing 5 hooks per week in Meta Ads before you scale spend.',
  'Make sure the landing page matches the ad copy word for word every time.'
].join(' ');

function makeLesson(script = CLEAN_SCRIPT, overrides = {}) {
  return buildLesson({
    source: SOURCE,
    transcript: makeTranscript(script),
    metadata: { title: 'Scaling ads', author: 'Some Creator', durationSeconds: 300 },
    strategy: 'yt-dlp',
    generatedAt: '2026-08-17T00:00:00.000Z',
    ...overrides
  });
}

test('renders a lesson with citations back to the source', () => {
  const lesson = makeLesson();
  const markdown = renderLessonMarkdown(lesson, proposeTasks(lesson));

  assert.match(markdown, /^# Scaling ads/);
  assert.match(markdown, /\*\*Creator:\*\* Some Creator/);
  assert.match(markdown, /Operational inference/, 'lessons are never presented as verified fact');
  assert.match(markdown, /https:\/\/www\.youtube\.com\/watch\?v=dQw4w9WgXcQ&t=\d+/, 'timestamp deep links');
  assert.match(markdown, /## Proposed work/);
  assert.match(markdown, /Nothing below has been executed/);
  assert.match(markdown, /## What was actually said/);
  assert.match(markdown, /Claimed by the creator, unverified/);
});

test('renders the same bytes for the same lesson', () => {
  const lesson = makeLesson();
  const proposals = proposeTasks(lesson);
  assert.equal(renderLessonMarkdown(lesson, proposals), renderLessonMarkdown(lesson, proposals));
});

test('puts an internal-only banner on non-compliant source material', () => {
  const lesson = makeLesson('Step one, you should inject 5mg twice a week for fat loss and better sleep.');
  const markdown = renderLessonMarkdown(lesson, proposeTasks(lesson));

  assert.match(markdown, /Internal reference only/);
  assert.match(markdown, /wellness\/dosing_language/);
  assert.match(markdown, /rewrite the words from scratch/);
});

test('warns when the transcript was too thin to conclude anything', () => {
  const markdown = renderLessonMarkdown(makeLesson('Always test one hook at a time.'), []);
  assert.match(markdown, /Thin transcript/);
});

test('surfaces the gating control on a proposal that would cross a hard limit', () => {
  const lesson = makeLesson();
  const markdown = renderLessonMarkdown(lesson, proposeTasks(lesson));
  assert.match(markdown, /Blocked pending owner action:.*spend cap/);
});

test('replaces an earlier pass over the same video instead of duplicating it', () => {
  const first = buildIndexEntry(makeLesson(), []);
  const second = buildIndexEntry(
    makeLesson(CLEAN_SCRIPT, { generatedAt: '2026-08-18T00:00:00.000Z' }),
    []
  );

  const merged = mergeIndex(mergeIndex([], first), second);
  assert.equal(merged.length, 1);
  assert.equal(merged[0].capturedAt, '2026-08-18T00:00:00.000Z', 'newest capture wins');

  const other = buildIndexEntry(
    buildLesson({
      source: parseVideoUrl('https://www.instagram.com/reel/Cx1yZ_abcDE/'),
      transcript: makeTranscript(CLEAN_SCRIPT),
      strategy: 'manual',
      generatedAt: '2026-08-16T00:00:00.000Z'
    }),
    []
  );
  const both = mergeIndex(merged, other);
  assert.equal(both.length, 2);
  assert.equal(both[0].capturedAt, '2026-08-18T00:00:00.000Z', 'sorted newest first');
});

test('renders and swaps the index block without touching the rest of the README', () => {
  const readme = `# Video Lessons\n\nSome prose.\n\n${INDEX_START}\n_No lessons captured yet._\n${INDEX_END}\n\nTrailing prose.\n`;
  const table = renderIndexTable([buildIndexEntry(makeLesson(), proposeTasks(makeLesson()))]);
  const updated = applyIndexBlock(readme, table);

  assert.match(updated, /Some prose\./);
  assert.match(updated, /Trailing prose\./);
  assert.doesNotMatch(updated, /_No lessons captured yet\._/);
  assert.match(updated, /\[Scaling ads\]\(youtube-dQw4w9WgXcQ\.md\)/);
});

test('escapes pipes so a title cannot break the index table', () => {
  const entry = buildIndexEntry(
    makeLesson(CLEAN_SCRIPT, { metadata: { title: 'Ads | Hooks | Scale' } }),
    []
  );
  assert.match(renderIndexTable([entry]), /Ads \\\| Hooks \\\| Scale/);
});

test('appends an index block to a README that has no markers yet', () => {
  const updated = applyIndexBlock('# Video Lessons\n', renderIndexTable([]));
  assert.match(updated, new RegExp(INDEX_START));
  assert.match(updated, /_No lessons captured yet\._/);
});

test('saves a lesson, its index, and the refreshed README', async () => {
  const baseDir = await fs.mkdtemp(path.join(os.tmpdir(), 'video-lesson-store-'));
  try {
    const lesson = makeLesson();
    const proposals = proposeTasks(lesson);
    const saved = await saveLesson({ lesson, proposals, baseDir, transcriptText: CLEAN_SCRIPT });

    assert.ok(saved.lessonPath.endsWith(path.join('video-lessons', 'youtube-dQw4w9WgXcQ.md')));
    assert.match(await fs.readFile(saved.lessonPath, 'utf8'), /# Scaling ads/);

    const index = JSON.parse(await fs.readFile(saved.indexPath, 'utf8'));
    assert.equal(index.length, 1);
    assert.equal(index[0].sourceKey, 'youtube-dQw4w9WgXcQ');
    assert.equal(index[0].proposalCount, proposals.length);

    assert.match(await fs.readFile(saved.readmePath, 'utf8'), /\[Scaling ads\]/);
    assert.equal(saved.transcriptPath, null, 'transcripts are not committed by default');

    // Re-processing the same video updates in place.
    const again = await saveLesson({
      lesson: makeLesson(CLEAN_SCRIPT, { generatedAt: '2026-08-18T00:00:00.000Z' }),
      proposals,
      baseDir
    });
    assert.equal(again.lessonPath, saved.lessonPath);
    assert.equal(JSON.parse(await fs.readFile(saved.indexPath, 'utf8')).length, 1);
  } finally {
    await fs.rm(baseDir, { recursive: true, force: true });
  }
});

test('writes the transcript only when explicitly asked', async () => {
  const baseDir = await fs.mkdtemp(path.join(os.tmpdir(), 'video-lesson-store-'));
  try {
    const saved = await saveLesson({
      lesson: makeLesson(),
      proposals: [],
      baseDir,
      transcriptText: CLEAN_SCRIPT,
      saveTranscript: true
    });
    assert.ok(saved.transcriptPath);
    assert.match(await fs.readFile(saved.transcriptPath, 'utf8'), /biggest mistake/);
  } finally {
    await fs.rm(baseDir, { recursive: true, force: true });
  }
});

test('reads links and their instructions out of the inbox', () => {
  const inbox = [
    '# Video Inbox',
    '',
    '> Instructions the owner should not have parsed as a link.',
    '',
    '## Queue',
    '',
    '- https://youtu.be/dQw4w9WgXcQ — build an ad angle from this',
    '- https://www.instagram.com/reel/Cx1yZ_abcDE/ | steal the hook structure',
    '* watch this one: https://www.youtube.com/shorts/abcdefghijk',
    '1. https://youtu.be/dQw4w9WgXcQ (duplicate, already queued above)',
    '- https://www.youtube.com/@somechannel — a channel, not a video',
    '- just a note with no link at all'
  ].join('\n');

  const { items, invalid } = parseInbox(inbox);

  assert.equal(items.length, 3, 'duplicates collapse to one entry');
  assert.equal(items[0].source.sourceKey, 'youtube-dQw4w9WgXcQ');
  assert.equal(items[0].task, 'build an ad angle from this');
  assert.equal(items[1].task, 'steal the hook structure');
  assert.equal(items[2].task, 'watch this one', 'instruction before the link still counts');

  // A typo has to surface, not vanish silently.
  assert.equal(invalid.length, 2);
  assert.match(invalid[0].reason, /not a single YouTube or Instagram video/);
  assert.match(invalid[1].reason, /no YouTube or Instagram link/);
});

test('ignores the inbox file\'s own documentation instead of queueing it', () => {
  // The shipped inbox.md is mostly prose plus a fenced example block. Reading
  // those as entries made the daily scheduled run fail every single day, and
  // made the placeholder reel below look like a real video to go and fetch.
  const inbox = [
    '# Video Inbox',
    '',
    'Drop YouTube or Instagram links here. One per line. Add what you want done',
    'with it after the link — a dash, a pipe, or a colon all work.',
    '',
    '```',
    '- https://youtu.be/VIDEOID — build an ad angle from this',
    '- https://www.instagram.com/reel/SHORTCODE | steal the hook structure',
    '- https://www.youtube.com/watch?v=VIDEOID',
    '```',
    '',
    'Anything queued below gets picked up by the **Video learning** workflow.',
    'Each processed link is turned into a lesson file in this folder.',
    '',
    '## Queue',
    '',
    '<!-- Add links below this line. -->'
  ].join('\n');

  const { items, invalid } = parseInbox(inbox);
  assert.equal(items.length, 0, 'documentation is not a queue');
  assert.equal(invalid.length, 0, 'and it must not report false failures either');
});

test('reads a real entry that follows the documentation', () => {
  const inbox = [
    'Drop links here. Example:',
    '',
    '```',
    '- https://youtu.be/VIDEOID — placeholder',
    '```',
    '',
    '## Queue',
    '',
    '- https://youtu.be/dQw4w9WgXcQ — build an ad angle',
    'https://www.instagram.com/reel/Cx1yZ_abcDE/'
  ].join('\n');

  const { items, invalid } = parseInbox(inbox);
  assert.equal(invalid.length, 0);
  assert.deepEqual(
    items.map((item) => item.source.sourceKey),
    ['youtube-dQw4w9WgXcQ', 'instagram-Cx1yZ_abcDE'],
    'a bullet and a bare pasted URL both count'
  );
  assert.equal(items[0].task, 'build an ad angle');
});

test('leaves fenced example links alone when clearing processed entries', () => {
  const inbox = [
    '```',
    '- https://youtu.be/dQw4w9WgXcQ — example in the docs',
    '```',
    '',
    '- https://youtu.be/dQw4w9WgXcQ — the real queued one'
  ].join('\n');

  const updated = removeProcessed(inbox, ['youtube-dQw4w9WgXcQ']);
  assert.match(updated, /example in the docs/, 'the documented example survives');
  assert.doesNotMatch(updated, /the real queued one/, 'the queued entry is cleared');
});

test('treats a link with no instruction as a plain capture', () => {
  const { items } = parseInbox('- https://youtu.be/dQw4w9WgXcQ');
  assert.equal(items[0].task, null);
});

test('removes only the processed links and leaves the rest queued', () => {
  const inbox = [
    '## Queue',
    '',
    '- https://youtu.be/dQw4w9WgXcQ — done',
    '- https://www.instagram.com/reel/Cx1yZ_abcDE/ — still pending',
    ''
  ].join('\n');

  const updated = removeProcessed(inbox, ['youtube-dQw4w9WgXcQ']);
  assert.doesNotMatch(updated, /dQw4w9WgXcQ/);
  assert.match(updated, /Cx1yZ_abcDE/);
  assert.match(updated, /## Queue/, 'structure survives');

  assert.equal(removeProcessed(inbox, []), inbox, 'nothing processed means nothing changes');
});
