'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const {
  extractJsonObject,
  extractCaptionTracks,
  pickCaptionTrack,
  parseJson3,
  parseTimedTextXml,
  parseVtt,
  parseSubtitleFile,
  parsePlainTranscript,
  segmentsToText,
  decodeEntities
} = require('../lib/video-learning/transcript-parsers');

test('extracts a JSON object from HTML by brace matching, not regex', () => {
  // Braces inside string literals are exactly what breaks a naive regex.
  const html = `<script>var ytInitialPlayerResponse = {"a":{"b":"}}not the end{{"},"c":1};</script>`;
  const extracted = extractJsonObject(html, 'ytInitialPlayerResponse');
  assert.equal(JSON.parse(extracted).c, 1);
  assert.equal(JSON.parse(extracted).a.b, '}}not the end{{');
});

test('returns null when the marker or object is absent', () => {
  assert.equal(extractJsonObject('<html></html>', 'ytInitialPlayerResponse'), null);
  assert.equal(extractJsonObject(null, 'ytInitialPlayerResponse'), null);
});

test('reads caption tracks out of a watch page payload', () => {
  const html = `<script>var ytInitialPlayerResponse = ${JSON.stringify({
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [
          { baseUrl: 'https://example.test/en-auto', languageCode: 'en', kind: 'asr', name: { simpleText: 'English (auto)' } },
          { baseUrl: 'https://example.test/en', languageCode: 'en', name: { simpleText: 'English' } },
          { languageCode: 'es' }
        ]
      }
    }
  })};</script>`;

  const tracks = extractCaptionTracks(html);
  // The track with no baseUrl is unusable and must be dropped.
  assert.equal(tracks.length, 2);
  assert.equal(tracks[0].autoGenerated, true);
  assert.equal(tracks[1].autoGenerated, false);
});

test('prefers a human-written English track over an auto-generated one', () => {
  const tracks = [
    { baseUrl: 'a', languageCode: 'en', autoGenerated: true },
    { baseUrl: 'b', languageCode: 'en', autoGenerated: false },
    { baseUrl: 'c', languageCode: 'de', autoGenerated: false }
  ];
  assert.equal(pickCaptionTrack(tracks).baseUrl, 'b');
  // English auto-captions still beat a foreign-language human track.
  assert.equal(pickCaptionTrack([tracks[0], tracks[2]]).baseUrl, 'a');
  assert.equal(pickCaptionTrack([]), null);
});

test('parses json3 captions into timed segments', () => {
  const body = JSON.stringify({
    events: [
      { tStartMs: 0, dDurationMs: 1500, segs: [{ utf8: 'the first ' }, { utf8: 'thing' }] },
      { tStartMs: 1500, dDurationMs: 1000 }, // no segs — a formatting event
      { tStartMs: 2000, dDurationMs: 1200, segs: [{ utf8: '\n' }] }, // whitespace only
      { tStartMs: 3000, dDurationMs: 900, segs: [{ utf8: 'you need to test' }] }
    ]
  });
  const segments = parseJson3(body);
  assert.equal(segments.length, 2);
  assert.deepEqual(segments[0], { start: 0, duration: 1.5, text: 'the first thing' });
  assert.equal(segments[1].start, 3);
});

test('parses legacy timedtext XML and decodes entities', () => {
  const body =
    '<transcript>' +
    '<text start="0" dur="2.5">hooks &amp; retention</text>' +
    '<text start="2.5" dur="3">that&#39;s the &quot;secret&quot;</text>' +
    '<text start="6" dur="1">[Music]</text>' +
    '</transcript>';
  const segments = parseTimedTextXml(body);
  assert.equal(segments.length, 2, 'sound-only annotations carry no instruction value');
  assert.equal(segments[0].text, 'hooks & retention');
  assert.equal(segments[1].text, `that's the "secret"`);
});

test('collapses YouTube rolling captions instead of repeating every line', () => {
  // Auto-generated VTT re-states the previous cue's text on each new cue.
  const body = [
    'WEBVTT',
    '',
    '00:00:01.000 --> 00:00:03.000',
    'the first thing',
    '',
    '00:00:03.000 --> 00:00:05.000',
    'the first thing you need',
    '',
    '00:00:05.000 --> 00:00:07.000',
    'the first thing you need to do',
    '',
    '00:00:07.000 --> 00:00:09.000',
    '<c.colorE5E5E5>is pick one channel</c>'
  ].join('\n');

  const segments = parseVtt(body);
  const text = segmentsToText(segments);
  assert.equal(text, 'the first thing you need to do is pick one channel');
  assert.equal(segments[0].duration, 2);
});

test('dispatches on file extension and sniffs unknown ones', () => {
  const vtt = 'WEBVTT\n\n00:00.000 --> 00:02.000\nhello there\n';
  assert.equal(parseSubtitleFile('captions.en.vtt', vtt)[0].text, 'hello there');
  assert.equal(parseSubtitleFile('captions.unknown', vtt)[0].text, 'hello there');

  const json3 = JSON.stringify({ events: [{ tStartMs: 0, dDurationMs: 1000, segs: [{ utf8: 'hi' }] }] });
  assert.equal(parseSubtitleFile('captions.en.json3', json3)[0].text, 'hi');
  assert.equal(parseSubtitleFile('captions.bin', json3)[0].text, 'hi');

  assert.deepEqual(parseSubtitleFile('captions.txt', 'not a caption file'), []);
});

test('parses a hand-pasted transcript with and without timestamps', () => {
  const segments = parsePlainTranscript(
    ['1:05 start with one offer', '[2:30] then scale it', 'no timestamp on this line', '   '].join('\n')
  );
  assert.equal(segments.length, 3);
  assert.equal(segments[0].start, 65);
  assert.equal(segments[0].text, 'start with one offer');
  assert.equal(segments[1].start, 150);
  assert.equal(segments[2].start, null);
});

test('decodes numeric and named entities', () => {
  assert.equal(decodeEntities('a &amp; b &#39;c&#39; &#x41;'), `a & b 'c' A`);
});
