'use strict';

// The backlog is regenerated from scratch on every run, so the behaviour that
// matters most is that regeneration never destroys the owner's progress.

const test = require('node:test');
const assert = require('node:assert/strict');

const { parseVideoUrl } = require('../lib/video-learning/video-sources');
const { buildLesson } = require('../lib/video-learning/lesson-extractor');
const { proposeTasks, proposalId } = require('../lib/video-learning/task-proposal');
const { buildIndexEntry } = require('../lib/video-learning/lesson-store');
const {
  renderBacklog,
  parseCheckedIds,
  collectProposals,
  groupByLane
} = require('../lib/video-learning/backlog');

const SCRIPT = [
  'The biggest mistake people make is launching twelve creatives at once.',
  'Step one, pick a single winning hook and hold it for two weeks.',
  'Never change the budget and the creative in the same week.',
  'I recommend testing 5 hooks per week in Meta Ads before you scale spend.'
].join(' ');

function makeTranscript(script) {
  const words = script.split(/\s+/).filter(Boolean);
  const segments = [];
  for (let i = 0; i < words.length; i += 4) {
    segments.push({ start: (i / 4) * 2, duration: 2, text: words.slice(i, i + 4).join(' ') });
  }
  return { segments, text: script, language: 'en', autoGenerated: false };
}

function makeEntry({
  url = 'https://youtu.be/dQw4w9WgXcQ',
  script = SCRIPT,
  title = 'Scaling ads',
  capturedAt = '2026-08-17T00:00:00.000Z'
} = {}) {
  const lesson = buildLesson({
    source: parseVideoUrl(url),
    transcript: makeTranscript(script),
    metadata: { title },
    strategy: 'yt-dlp',
    generatedAt: capturedAt
  });
  return buildIndexEntry(lesson, proposeTasks(lesson));
}

test('proposal ids are stable across re-extraction and unique per video', () => {
  const first = makeEntry();
  const second = makeEntry({ capturedAt: '2026-09-01T00:00:00.000Z' });
  assert.deepEqual(
    first.proposals.map((proposal) => proposal.id),
    second.proposals.map((proposal) => proposal.id),
    're-processing the same video must re-derive the same ids'
  );

  // The same sentence in a different video is a different piece of work.
  assert.notEqual(
    proposalId('youtube-dQw4w9WgXcQ', 'Never change the budget'),
    proposalId('instagram-Cx1yZ_abcDE', 'Never change the budget')
  );
});

test('renders every proposal grouped by lane with its citation', () => {
  const markdown = renderBacklog([makeEntry()]);

  assert.match(markdown, /^# Video Lesson Backlog/);
  assert.match(markdown, /\*\*Nothing here has been executed\*\*/);
  assert.match(markdown, /## Paid advertising \(\d+ open\)/);
  assert.match(markdown, /from \[Scaling ads\]\(youtube-dQw4w9WgXcQ\.md\)/);
  assert.match(markdown, /&t=\d+\)/, 'citations survive into the backlog');
  assert.match(markdown, /- \[ \] \*\*/, 'items start unticked');
});

test('flags proposals that are blocked on an owner decision', () => {
  const markdown = renderBacklog([makeEntry()]);
  assert.match(markdown, /⚠ .*spend cap/);
  assert.match(markdown, /awaiting an owner decision/);
});

test('marks non-compliant source wording as internal only', () => {
  const entry = makeEntry({
    script: 'Step one, you should inject 5mg twice a week for fat loss every week.'
  });
  const markdown = renderBacklog([entry]);
  assert.match(markdown, /Internal wording only/);
});

test('reads ticked items back out of an existing backlog', () => {
  const markdown = [
    '- [x] **Adopt: something** <!-- id:abc1234567 -->',
    '- [ ] **Trial: something else** <!-- id:def8901234 -->',
    '- [X] **Audit for: third** <!-- id:AAA1111111 -->',
    '- [x] a ticked line with no id marker',
    'not a checklist line at all'
  ].join('\n');

  const checked = parseCheckedIds(markdown);
  assert.ok(checked.has('abc1234567'));
  assert.ok(checked.has('aaa1111111'), 'ids are compared case-insensitively');
  assert.ok(!checked.has('def8901234'), 'unticked items are not carried over');
  assert.equal(checked.size, 2);
  assert.equal(parseCheckedIds('').size, 0);
});

test('a ticked item survives regeneration', () => {
  const entry = makeEntry();
  const first = renderBacklog([entry]);

  // Simulate the owner ticking the first box.
  const targetId = entry.proposals[0].id;
  const ticked = first.replace(`- [ ] **${entry.proposals[0].title}**`, `- [x] **${entry.proposals[0].title}**`);
  assert.notEqual(ticked, first, 'test setup: the box must actually change');

  const regenerated = renderBacklog([entry], { checkedIds: parseCheckedIds(ticked) });
  assert.match(regenerated, new RegExp(`- \\[x\\] \\*\\*[^\\n]*<!-- id:${targetId} -->`));

  // And the round trip is stable: re-reading the regenerated file agrees.
  assert.ok(parseCheckedIds(regenerated).has(targetId));
});

test('completed work sinks below open work within its lane', () => {
  const entry = makeEntry();
  const adsProposals = entry.proposals.filter((proposal) => proposal.lane === 'paid-ads');
  assert.ok(adsProposals.length >= 2, 'test setup needs at least two items in a lane');

  const doneId = adsProposals[0].id;
  const markdown = renderBacklog([entry], { checkedIds: new Set([doneId]) });

  const adsSection = markdown.split('## ').find((section) => section.startsWith('Paid advertising'));
  const tickedIndex = adsSection.indexOf(`id:${doneId}`);
  const firstOpenIndex = adsSection.indexOf('- [ ]');
  assert.ok(firstOpenIndex !== -1 && tickedIndex > firstOpenIndex, 'open work stays on top');
});

test('counts only open items in the header and lane headings', () => {
  const entry = makeEntry();
  const total = entry.proposals.length;
  const doneId = entry.proposals[0].id;

  assert.match(renderBacklog([entry]), new RegExp(`${total} open of ${total} proposals`));
  assert.match(
    renderBacklog([entry], { checkedIds: new Set([doneId]) }),
    new RegExp(`${total - 1} open of ${total} proposals`)
  );
});

test('merges proposals from several videos and reports the video count', () => {
  const entries = [
    makeEntry(),
    makeEntry({
      url: 'https://www.instagram.com/reel/Cx1yZ_abcDE/',
      title: 'Reel tactics',
      capturedAt: '2026-08-18T00:00:00.000Z'
    })
  ];
  const markdown = renderBacklog(entries);

  assert.match(markdown, /from 2 videos/);
  assert.match(markdown, /\[Scaling ads\]/);
  assert.match(markdown, /\[Reel tactics\]/);
  assert.equal(collectProposals(entries).length, entries[0].proposals.length * 2);
});

test('the general lane sorts last even when it is the largest', () => {
  const proposals = [
    { lane: 'general' },
    { lane: 'general' },
    { lane: 'general' },
    { lane: 'paid-ads' }
  ];
  assert.deepEqual(
    groupByLane(proposals).map(([lane]) => lane),
    ['paid-ads', 'general'],
    'the fallback bucket never leads the list'
  );
});

test('says so plainly when nothing has been captured yet', () => {
  const markdown = renderBacklog([]);
  assert.match(markdown, /No proposals yet/);
  assert.match(markdown, /inbox\.md/);
});
