'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const { parseVideoUrl } = require('../lib/video-learning/video-sources');
const {
  buildLesson,
  buildUtterances,
  selectActions,
  selectMetrics,
  detectTools,
  evaluateReuse
} = require('../lib/video-learning/lesson-extractor');
const { proposeTasks, classifyLane, ownerGateFor, condense } = require('../lib/video-learning/task-proposal');

const SOURCE = parseVideoUrl('https://youtu.be/dQw4w9WgXcQ');

// A marketing video, chopped the way real auto-captions arrive: a few words
// per cue, two seconds apart.
const SCRIPT = [
  "Here's how we scaled the ad account to 3x return in 90 days.",
  'The biggest mistake people make is launching twelve creatives at once.',
  'Step one, pick a single winning hook and hold it for two weeks.',
  'Never change the budget and the creative in the same week.',
  'What I do is check the CPM every morning and keep it at $40 or below.',
  'Make sure the landing page matches the ad copy word for word.',
  'I recommend testing 5 hooks per week in Meta Ads before you scale spend.'
].join(' ');

function captionize(script, { wordsPerSegment = 4, secondsPerSegment = 2 } = {}) {
  const words = script.split(/\s+/).filter(Boolean);
  const segments = [];
  for (let i = 0; i < words.length; i += wordsPerSegment) {
    segments.push({
      start: (i / wordsPerSegment) * secondsPerSegment,
      duration: secondsPerSegment,
      text: words.slice(i, i + wordsPerSegment).join(' ')
    });
  }
  return { segments, text: script, language: 'en', autoGenerated: true };
}

const TRANSCRIPT = captionize(SCRIPT);

test('rebuilds sentences from fragmented caption cues', () => {
  const utterances = buildUtterances(TRANSCRIPT.segments);
  assert.equal(utterances.length, 7, 'one utterance per spoken sentence');
  assert.equal(utterances[0].text, "Here's how we scaled the ad account to 3x return in 90 days.");
  assert.equal(utterances[0].start, 0, 'keeps the timestamp of its first cue');
  assert.ok(utterances[1].start > 0);
});

test('closes an utterance on a pause even without punctuation', () => {
  // Machine captions with no punctuation at all: the gap is the only boundary.
  const segments = [
    { start: 0, duration: 2, text: 'pick one channel and go deep' },
    { start: 2, duration: 2, text: 'instead of spreading thin' },
    { start: 30, duration: 2, text: 'now about the offer itself' }
  ];
  const utterances = buildUtterances(segments);
  assert.equal(utterances.length, 2, 'a 26-second silence ends the utterance');
  assert.equal(utterances[1].text, 'now about the offer itself');
});

test('extracts instructional lines and labels why each one qualified', () => {
  const actions = selectActions(buildUtterances(TRANSCRIPT.segments));
  const cues = actions.map((action) => action.cue);
  assert.ok(cues.includes('mistake'), 'the "biggest mistake" line is instructional');
  assert.ok(cues.includes('step'));
  assert.ok(cues.includes('rule'));
  assert.ok(cues.includes('recommendation'));

  const mistake = actions.find((action) => action.cue === 'mistake');
  assert.match(mistake.text, /launching twelve creatives/);
  assert.ok(Number.isFinite(mistake.start), 'every action carries a timestamp to cite');
});

test('captures the concrete numbers a creator states', () => {
  const metrics = selectMetrics(buildUtterances(TRANSCRIPT.segments));
  const values = metrics.flatMap((metric) => metric.values.map((value) => value.toLowerCase()));
  assert.ok(values.includes('3x'));
  // Both numbers in "3x return in 90 days" must survive, not just the first.
  assert.ok(values.includes('90 days'));
  assert.ok(values.includes('$40'));
});

test('recognizes the platforms this business actually uses', () => {
  const tools = detectTools(SCRIPT);
  assert.ok(tools.some((tool) => tool.name === 'Meta Ads'));
  assert.deepEqual(detectTools('nothing relevant here at all'), []);
});

test('builds a complete lesson with provenance intact', () => {
  const lesson = buildLesson({
    source: SOURCE,
    transcript: TRANSCRIPT,
    metadata: { title: 'Scaling ads', author: 'Some Creator', durationSeconds: 300 },
    strategy: 'yt-dlp',
    task: 'build an ad angle',
    generatedAt: '2026-08-17T00:00:00.000Z'
  });

  assert.equal(lesson.transcript.strategy, 'yt-dlp');
  assert.equal(lesson.transcript.autoGenerated, true);
  assert.equal(lesson.transcript.thin, false);
  assert.equal(lesson.task, 'build an ad angle');
  assert.equal(lesson.transcript.durationSeconds, 300);
  assert.ok(lesson.summary.length > 0);
  assert.ok(lesson.actions.length >= 4);
  assert.ok(lesson.topics.length > 0);
  // Filler words must not dominate the topic list.
  assert.ok(!lesson.topics.some((topic) => ['really', 'like', 'guys'].includes(topic.term)));
});

test('flags a transcript too short to draw conclusions from', () => {
  const lesson = buildLesson({
    source: SOURCE,
    transcript: captionize('You should always test one hook at a time.'),
    strategy: 'manual'
  });
  assert.equal(lesson.transcript.thin, true);
});

test('refuses to build a lesson without a transcript', () => {
  assert.throws(() => buildLesson({ source: SOURCE, transcript: null }), TypeError);
  assert.throws(() => buildLesson({ source: SOURCE, transcript: { text: '   ' } }), TypeError);
  assert.throws(() => buildLesson({ transcript: TRANSCRIPT }), TypeError);
});

test('clean marketing language passes both brand gates', () => {
  const reuse = evaluateReuse(SCRIPT);
  assert.equal(reuse.wellnessSafe, true);
  assert.equal(reuse.beautySafe, true);
  assert.equal(reuse.internalOnly, false);
});

test('marks a lesson internal-only when the creator uses human-use language', () => {
  // Exactly the language a fitness creator uses and Lion Elite Wellness cannot.
  const reuse = evaluateReuse('You should inject 5mg twice a week and it will boost your energy.');
  assert.equal(reuse.wellnessSafe, false);
  assert.equal(reuse.internalOnly, true);
  const codes = reuse.wellnessBlockers.map((blocker) => blocker.code);
  assert.ok(codes.includes('dosing_language'));
  assert.ok(codes.includes('human_use_language'));
});

test('keeps research compounds out of the coaching brand', () => {
  const reuse = evaluateReuse('Offer your clients a peptide stack alongside the coaching.');
  assert.equal(reuse.beautySafe, false);
  assert.equal(reuse.beautyBlockers[0].code, 'brand_separation');
  assert.equal(reuse.internalOnly, true);
});

test('routes a tactic to the business lane it belongs to', () => {
  assert.equal(classifyLane('cut the ad spend on that campaign').id, 'paid-ads');
  assert.equal(classifyLane('rewrite the email subject line').id, 'outreach');
  assert.equal(classifyLane('the hook in the first three seconds').id, 'content');
  assert.equal(classifyLane('run the cap rate before you offer').id, 'real-estate');
  assert.equal(classifyLane('just be a nicer person').id, 'general');
});

test('flags tactics that would cross a hard limit with the control that gates them', () => {
  assert.match(ownerGateFor('send this to your whole list tomorrow'), /OUTREACH_SEND_ENABLED/);
  assert.match(ownerGateFor('text them a reminder the next day'), /SMS_SEND_ENABLED/);
  assert.match(ownerGateFor('publish it across every account'), /SOCIAL_PUBLISH_ENABLED/);
  assert.match(ownerGateFor('increase the budget once it works'), /spend cap/);
  assert.match(ownerGateFor('buy the pro plan for that'), /owner authorization/);
  assert.equal(ownerGateFor('write a better hook'), null);
});

test('proposes work without executing any of it', () => {
  const lesson = buildLesson({
    source: SOURCE,
    transcript: TRANSCRIPT,
    strategy: 'yt-dlp',
    generatedAt: '2026-08-17T00:00:00.000Z'
  });
  const proposals = proposeTasks(lesson);

  assert.ok(proposals.length > 0);
  for (const proposal of proposals) {
    assert.ok(proposal.title.length > 0);
    assert.ok(proposal.quote.length > 0, 'every proposal quotes its source line');
    assert.ok(proposal.citation.url.includes('t='), 'and links to the timestamp');
    assert.equal(proposal.customerFacingSafe, true);
  }

  assert.ok(
    proposals.some((proposal) => proposal.lane === 'paid-ads'),
    'an ads video should produce ads-lane proposals'
  );
  assert.ok(
    proposals.some((proposal) => proposal.requiresOwnerAction && /spend cap/.test(proposal.ownerActionReason)),
    'the "scale spend" line must surface the spend cap'
  );
});

test('proposals inherit the lesson compliance verdict', () => {
  const lesson = buildLesson({
    source: SOURCE,
    transcript: captionize(
      'Step one, you should inject 5mg twice a week. Never skip a day if you want fat loss results.'
    ),
    strategy: 'manual'
  });
  const proposals = proposeTasks(lesson);
  assert.ok(proposals.length > 0);
  assert.ok(
    proposals.every((proposal) => proposal.customerFacingSafe === false),
    'nothing from a non-compliant source may be marked safe to ship'
  );
});

test('condenses a long quote into a readable title without cutting mid-word', () => {
  const long = 'And so the thing you really need to do here is build one single offer that people actually want to buy';
  const title = condense(long, 40);
  assert.ok(title.length <= 41, 'stays within the budget');
  assert.ok(title.endsWith('…'));
  assert.ok(!title.startsWith('And so'), 'drops the leading filler');
  assert.equal(condense('short line.'), 'short line');
});
