'use strict';

// Covers the strategy ladder in fetchTranscript(): which source of truth wins,
// what happens when each one is unavailable, and the fail-closed result.
//
// This is the part of the pipeline that cannot be exercised in the dev sandbox
// (the proxy blocks youtube.com and instagram.com) or in CI without installing
// yt-dlp, so every side effect is injected. What is being tested here is the
// decision logic, not the network.

const test = require('node:test');
const assert = require('node:assert/strict');

const { parseVideoUrl } = require('../lib/video-learning/video-sources');
const {
  fetchTranscript,
  buildManualTranscript,
  extractPageMetadata,
  resolveWhisperConfig
} = require('../lib/video-learning/transcript-fetcher');

const YOUTUBE = parseVideoUrl('https://youtu.be/dQw4w9WgXcQ');
const INSTAGRAM = parseVideoUrl('https://www.instagram.com/reel/Cx1yZ_abcDE/');

const TRANSCRIPT = {
  segments: [{ start: 0, duration: 2, text: 'never change two things at once' }],
  text: 'never change two things at once',
  language: 'en',
  autoGenerated: false
};

/** Every dependency off by default; each test switches on only what it needs. */
function makeDeps(overrides = {}) {
  const calls = [];
  const record = (name) => calls.push(name);
  const deps = {
    hasBinary: async (binary) => {
      record(`hasBinary:${binary}`);
      return false;
    },
    ytDlpMetadata: async () => {
      record('ytDlpMetadata');
      return {};
    },
    ytDlpSubtitles: async () => {
      record('ytDlpSubtitles');
      return null;
    },
    fetchYouTubePage: async () => {
      record('fetchYouTubePage');
      return '<html></html>';
    },
    fetchYouTubePageTranscript: async () => {
      record('fetchYouTubePageTranscript');
      return null;
    },
    transcribeWithWhisper: async () => {
      record('transcribeWithWhisper');
      return null;
    },
    ...overrides
  };
  return { deps, calls };
}

function attemptFor(result, strategy) {
  return result.attempts.find((attempt) => attempt.strategy === strategy);
}

test('a supplied transcript wins outright and skips every other strategy', async () => {
  const { deps, calls } = makeDeps();
  const result = await fetchTranscript({
    source: YOUTUBE,
    manualTranscript: '0:05 never change two things at once',
    deps
  });

  assert.equal(result.status, 'ok');
  assert.equal(result.strategy, 'manual');
  assert.equal(result.transcript.segments[0].start, 5);
  assert.deepEqual(calls, [], 'no binary probe, no network, nothing paid');
});

test('an empty supplied transcript is recorded and falls through', async () => {
  const { deps } = makeDeps();
  const result = await fetchTranscript({
    source: YOUTUBE,
    manualTranscript: '   \n  \n ',
    env: {},
    deps
  });

  // Whitespace never reaches the manual branch, so it just falls through.
  assert.equal(result.status, 'needs_manual');
  assert.equal(result.transcript, null);
});

test('a supplied transcript with no usable text records the failure', async () => {
  const { deps } = makeDeps();
  const result = await fetchTranscript({
    source: YOUTUBE,
    // Non-empty, but every line is a sound annotation the parser strips.
    manualTranscript: '[Music]\n[Applause]',
    env: {},
    deps
  });

  assert.equal(result.status, 'needs_manual');
  assert.match(attemptFor(result, 'manual').detail, /no usable text/);
});

test('yt-dlp captions win when the binary is present', async () => {
  const { deps } = makeDeps({
    hasBinary: async () => true,
    ytDlpMetadata: async () => ({ title: 'Real title', author: 'Real creator', durationSeconds: 300 }),
    ytDlpSubtitles: async () => TRANSCRIPT
  });

  const result = await fetchTranscript({ source: YOUTUBE, deps });

  assert.equal(result.status, 'ok');
  assert.equal(result.strategy, 'yt-dlp');
  assert.equal(result.metadata.title, 'Real title');
  assert.equal(result.metadata.durationSeconds, 300);
});

test('falls back to the watch page when yt-dlp is missing', async () => {
  const { deps, calls } = makeDeps({
    fetchYouTubePageTranscript: async () => TRANSCRIPT
  });

  const result = await fetchTranscript({ source: YOUTUBE, deps });

  assert.equal(result.status, 'ok');
  assert.equal(result.strategy, 'youtube-page');
  assert.match(attemptFor(result, 'yt-dlp').detail, /not installed/);
  assert.ok(calls.includes('fetchYouTubePage'));
  assert.ok(!calls.includes('ytDlpSubtitles'), 'a missing binary is never invoked');
});

test('falls back to the watch page when yt-dlp is present but finds no captions', async () => {
  const { deps } = makeDeps({
    hasBinary: async () => true,
    ytDlpSubtitles: async () => null,
    fetchYouTubePageTranscript: async () => TRANSCRIPT
  });

  const result = await fetchTranscript({ source: YOUTUBE, deps });

  assert.equal(result.strategy, 'youtube-page');
  assert.match(attemptFor(result, 'yt-dlp').detail, /no caption track available/);
});

test('a crashing strategy is recorded and does not abort the ladder', async () => {
  const { deps } = makeDeps({
    hasBinary: async () => true,
    ytDlpSubtitles: async () => {
      const error = new Error('exited with code 1');
      error.stderr = 'ERROR: Private video. Sign in if you have been granted access.';
      throw error;
    },
    fetchYouTubePageTranscript: async () => TRANSCRIPT
  });

  const result = await fetchTranscript({ source: YOUTUBE, deps });

  assert.equal(result.status, 'ok', 'one broken strategy must not sink the run');
  assert.match(attemptFor(result, 'yt-dlp').detail, /Private video/, 'surfaces the real reason');
});

test('richer yt-dlp metadata is not overwritten by the watch page', async () => {
  const { deps } = makeDeps({
    hasBinary: async () => true,
    ytDlpMetadata: async () => ({ title: 'Canonical title', author: 'Canonical creator' }),
    ytDlpSubtitles: async () => null,
    fetchYouTubePage: async () =>
      '<meta property="og:title" content="SEO title"><meta property="video:duration" content="425">',
    fetchYouTubePageTranscript: async () => TRANSCRIPT
  });

  const result = await fetchTranscript({ source: YOUTUBE, deps });

  assert.equal(result.metadata.title, 'Canonical title');
  assert.equal(result.metadata.author, 'Canonical creator');
  // The page still contributes what yt-dlp did not have.
  assert.equal(result.metadata.durationSeconds, 425);
});

test('the watch-page strategy is never tried for Instagram', async () => {
  const { deps, calls } = makeDeps();
  const result = await fetchTranscript({ source: INSTAGRAM, env: {}, deps });

  assert.equal(result.status, 'needs_manual');
  assert.ok(!calls.includes('fetchYouTubePage'), 'scraping a YouTube page for a reel is nonsense');
  assert.equal(attemptFor(result, 'youtube-page'), undefined);
  assert.match(result.guidance, /Instagram does not expose captions/);
});

test('the paid audio path stays off unless everything for it is present', async () => {
  const cases = [
    {
      name: 'explicitly disabled',
      input: { allowWhisper: false, env: { AI_API_KEY: 'sk-test' }, deps: makeDeps({ hasBinary: async () => true }).deps },
      expect: /disabled for this run/
    },
    {
      name: 'no yt-dlp to download audio',
      input: { env: { AI_API_KEY: 'sk-test' }, deps: makeDeps().deps },
      expect: /needs yt-dlp/
    },
    {
      name: 'no API key',
      input: { env: {}, deps: makeDeps({ hasBinary: async () => true }).deps },
      expect: /no AI_API_KEY/
    },
    {
      name: 'no ffmpeg',
      input: {
        env: { AI_API_KEY: 'sk-test' },
        deps: makeDeps({ hasBinary: async (binary) => binary !== 'ffmpeg' }).deps
      },
      expect: /ffmpeg is not installed/
    }
  ];

  for (const { name, input, expect } of cases) {
    const result = await fetchTranscript({ source: YOUTUBE, ...input });
    const attempt = attemptFor(result, 'whisper');
    assert.equal(attempt.ok, false, name);
    assert.match(attempt.detail, expect, name);
  }
});

test('audio transcription runs only when yt-dlp, ffmpeg, and a key are all present', async () => {
  const { deps } = makeDeps({
    hasBinary: async () => true,
    transcribeWithWhisper: async () => TRANSCRIPT
  });

  const result = await fetchTranscript({
    source: YOUTUBE,
    env: { AI_API_KEY: 'sk-test' },
    deps
  });

  // A 'whisper' strategy can only be reported if the transcriber actually ran.
  assert.equal(result.status, 'ok');
  assert.equal(result.strategy, 'whisper');
  assert.equal(attemptFor(result, 'whisper').ok, true);
});

test('when every strategy fails it returns no transcript and explains each one', async () => {
  const { deps } = makeDeps({ hasBinary: async () => true });

  const result = await fetchTranscript({ source: YOUTUBE, env: {}, deps });

  assert.equal(result.status, 'needs_manual');
  assert.equal(result.transcript, null, 'never fabricate a transcript');
  assert.equal(result.strategy, null);
  assert.match(result.guidance, /--transcript-file/);

  // Every attempt is accounted for, so a failure is diagnosable from the log.
  for (const strategy of ['yt-dlp', 'youtube-page', 'whisper']) {
    const attempt = attemptFor(result, strategy);
    assert.ok(attempt, `expected an attempt record for ${strategy}`);
    assert.equal(attempt.ok, false);
    assert.ok(attempt.detail.length > 0);
  }
});

test('refuses to run without a parsed source', async () => {
  await assert.rejects(() => fetchTranscript({}), TypeError);
  await assert.rejects(() => fetchTranscript({ source: { platform: 'youtube' } }), TypeError);
});

test('reads the API key from either supported variable name', () => {
  assert.equal(resolveWhisperConfig({ AI_API_KEY: 'a' }).enabled, true);
  assert.equal(resolveWhisperConfig({ OPENAI_API_KEY: 'b' }).enabled, true);
  assert.equal(resolveWhisperConfig({}).enabled, false);
  assert.equal(resolveWhisperConfig({}).model, 'whisper-1');
  assert.equal(resolveWhisperConfig({ VIDEO_TRANSCRIBE_MODEL: 'custom' }).model, 'custom');
});

test('pulls title, creator, and duration out of watch-page metadata', () => {
  const metadata = extractPageMetadata(
    '<meta property="og:title" content="Scaling ads">' +
      '<meta content="Some Creator" name="author">' +
      '<meta property="video:duration" content="425">'
  );
  assert.equal(metadata.title, 'Scaling ads');
  assert.equal(metadata.author, 'Some Creator', 'attribute order varies across pages');
  assert.equal(metadata.durationSeconds, 425);
});

test('builds a manual transcript only from text that survives cleaning', () => {
  assert.equal(buildManualTranscript('[Music]'), null, 'sound annotations are not content');
  assert.equal(buildManualTranscript(''), null);
  assert.equal(buildManualTranscript('real content here').segments.length, 1);
});
