'use strict';

// Render and persist video lessons into the knowledge base.
//
// Lessons are keyed by source, not by date, so re-processing the same video
// updates its file in place instead of accumulating near-duplicate notes. The
// index is regenerated from index.json every save, which keeps the human
// table and the machine record from drifting apart.
//
// Full transcripts are deliberately NOT written to the repo by default. They
// are someone else's copyrighted words, they bloat the diff, and the lesson
// already cites the exact timestamp for anything worth re-reading. Pass
// saveTranscript when a working copy is genuinely needed.

const fs = require('node:fs/promises');
const path = require('node:path');

const { formatTimestamp, timestampedUrl } = require('./video-sources');
const { summarizeLanes } = require('./task-proposal');
const { renderBacklog, parseCheckedIds, BACKLOG_FILE } = require('./backlog');

const DEFAULT_LESSON_DIR = path.join('knowledge', 'video-lessons');
const INDEX_START = '<!-- lesson-index:start -->';
const INDEX_END = '<!-- lesson-index:end -->';

function escapeCell(text) {
  return String(text || '')
    .replace(/\|/g, '\\|')
    .replace(/\s*\n\s*/g, ' ')
    .trim();
}

function bulletWithCitation(source, item) {
  const label = formatTimestamp(item.start);
  if (!label) return `- ${item.text}`;
  return `- [\`${label}\`](${timestampedUrl(source, item.start)}) ${item.text}`;
}

function lessonTitle(lesson) {
  return (
    lesson.metadata?.title ||
    `${lesson.source.platform === 'youtube' ? 'YouTube' : 'Instagram'} ${lesson.source.kind} ${lesson.source.videoId}`
  );
}

/**
 * Render one lesson as the markdown file that lands in the knowledge base.
 * Pure: the same lesson always produces the same bytes.
 */
function renderLessonMarkdown(lesson, proposals = []) {
  const { source, metadata, transcript, reuse } = lesson;
  const lines = [];

  lines.push(`# ${lessonTitle(lesson)}`);
  lines.push('');
  lines.push('**Status:** Operational inference — extracted from a third-party video, not an owner-verified fact.');
  lines.push('');
  lines.push(`- **Source:** [${source.canonicalUrl}](${source.canonicalUrl}) (${source.platform}, ${source.kind})`);
  if (metadata?.author) lines.push(`- **Creator:** ${metadata.author}`);
  if (Number.isFinite(transcript.durationSeconds)) {
    lines.push(`- **Length:** ${formatTimestamp(transcript.durationSeconds)}`);
  }
  lines.push(`- **Captured:** ${lesson.generatedAt}`);
  lines.push(
    `- **Transcript:** ${transcript.strategy} · ${transcript.wordCount} words · ` +
      `${transcript.autoGenerated ? 'machine-generated captions' : 'human-written captions'}`
  );
  if (lesson.task) lines.push(`- **Owner asked for:** ${lesson.task}`);
  lines.push('');

  if (transcript.thin) {
    lines.push(
      '> **Thin transcript.** Fewer than 120 words were recovered, so treat every ' +
        'extraction below as a pointer to the source rather than a reliable summary.'
    );
    lines.push('');
  }

  if (reuse.internalOnly) {
    lines.push('> **Internal reference only — do not reuse this wording in customer-facing copy.**');
    lines.push('>');
    lines.push('> The source language trips Lion Elite brand compliance:');
    const blockerCodes = [
      ...new Set([
        ...reuse.wellnessBlockers.map((blocker) => `wellness/${blocker.code}`),
        ...reuse.beautyBlockers.map((blocker) => `beauty/${blocker.code}`)
      ])
    ];
    lines.push(`> ${blockerCodes.join(', ')}`);
    lines.push('>');
    lines.push('> Adopt the underlying mechanism if it is sound; rewrite the words from scratch.');
    lines.push('');
  }

  if (lesson.summary.length > 0) {
    lines.push('## Summary');
    lines.push('');
    for (const item of lesson.summary) lines.push(bulletWithCitation(source, item));
    lines.push('');
  }

  if (proposals.length > 0) {
    lines.push('## Proposed work');
    lines.push('');
    lines.push('Nothing below has been executed. Each item is a proposal for the owner to accept or drop.');
    lines.push('');
    for (const proposal of proposals) {
      const citation = proposal.citation
        ? ` ([\`${proposal.citation.label}\`](${proposal.citation.url}))`
        : '';
      lines.push(`### ${proposal.title}`);
      lines.push('');
      lines.push(`- **Lane:** ${proposal.laneLabel}`);
      lines.push(`- **Source line:**${citation} "${proposal.quote}"`);
      if (proposal.requiresOwnerAction) {
        lines.push(`- **Blocked pending owner action:** ${proposal.ownerActionReason}`);
      }
      if (!proposal.customerFacingSafe) {
        lines.push('- **Wording:** internal only — rewrite before anything ships.');
      }
      lines.push('');
    }
  }

  if (lesson.actions.length > 0) {
    lines.push('## What was actually said');
    lines.push('');
    for (const action of lesson.actions) {
      lines.push(`${bulletWithCitation(source, action)} _(${action.cue})_`);
    }
    lines.push('');
  }

  if (lesson.metrics.length > 0) {
    lines.push('## Numbers stated');
    lines.push('');
    lines.push('Claimed by the creator, unverified by Lion Elite.');
    lines.push('');
    for (const metric of lesson.metrics) lines.push(bulletWithCitation(source, metric));
    lines.push('');
  }

  if (lesson.tools.length > 0) {
    lines.push('## Tools and platforms mentioned');
    lines.push('');
    lines.push(lesson.tools.map((tool) => `${tool.name} (${tool.mentions})`).join(' · '));
    lines.push('');
  }

  if (lesson.chapters.length > 0) {
    lines.push('## Chapters');
    lines.push('');
    for (const chapter of lesson.chapters) {
      lines.push(
        `- [\`${formatTimestamp(chapter.start)}\`](${timestampedUrl(source, chapter.start)}) ${chapter.title}`
      );
    }
    lines.push('');
  }

  if (lesson.topics.length > 0) {
    lines.push('## Topics');
    lines.push('');
    lines.push(lesson.topics.map((topic) => `\`${topic.term}\``).join(' · '));
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

/** One row of the machine-readable index. */
function buildIndexEntry(lesson, proposals) {
  return {
    sourceKey: lesson.source.sourceKey,
    platform: lesson.source.platform,
    url: lesson.source.canonicalUrl,
    title: lessonTitle(lesson),
    creator: lesson.metadata?.author || null,
    capturedAt: lesson.generatedAt,
    task: lesson.task || null,
    file: `${lesson.source.sourceKey}.md`,
    transcriptStrategy: lesson.transcript.strategy,
    wordCount: lesson.transcript.wordCount,
    proposalCount: proposals.length,
    lanes: summarizeLanes(proposals).map((lane) => lane.lane),
    internalOnly: Boolean(lesson.reuse?.internalOnly),
    // Kept in the index so the cross-lesson backlog can be rebuilt from this
    // one file rather than re-parsing every lesson's markdown.
    proposals
  };
}

/** Merge one entry into the index, replacing any earlier pass over the same video. */
function mergeIndex(existing, entry) {
  const entries = Array.isArray(existing) ? existing.filter((row) => row.sourceKey !== entry.sourceKey) : [];
  entries.push(entry);
  return entries.sort((a, b) => String(b.capturedAt).localeCompare(String(a.capturedAt)));
}

/** Render the human-readable index table from the machine index. */
function renderIndexTable(entries) {
  if (!entries || entries.length === 0) {
    return '_No lessons captured yet._';
  }
  const rows = [
    '| Lesson | Source | Captured | Proposals | Reuse |',
    '| --- | --- | --- | --- | --- |'
  ];
  for (const entry of entries) {
    rows.push(
      `| [${escapeCell(entry.title)}](${entry.file}) | [${entry.platform}](${entry.url}) | ` +
        `${escapeCell(entry.capturedAt.slice(0, 10))} | ${entry.proposalCount} | ` +
        `${entry.internalOnly ? 'internal only' : 'clear'} |`
    );
  }
  return rows.join('\n');
}

/** Replace the marker-delimited index block inside the folder README. */
function applyIndexBlock(readme, table) {
  const block = `${INDEX_START}\n${table}\n${INDEX_END}`;
  if (readme.includes(INDEX_START) && readme.includes(INDEX_END)) {
    const pattern = new RegExp(`${INDEX_START}[\\s\\S]*?${INDEX_END}`);
    return readme.replace(pattern, block);
  }
  return `${readme.trimEnd()}\n\n${block}\n`;
}

async function readJsonIfPresent(filePath, fallback) {
  try {
    return JSON.parse(await fs.readFile(filePath, 'utf8'));
  } catch {
    return fallback;
  }
}

/**
 * Write a lesson, its index entry, and the refreshed README table.
 *
 * @param {object} input
 * @param {object} input.lesson
 * @param {Array} [input.proposals]
 * @param {string} [input.baseDir] - repo root
 * @param {string} [input.lessonDir] - relative lesson directory
 * @param {string} [input.transcriptText] - raw transcript, written only when
 *   saveTranscript is true
 * @param {boolean} [input.saveTranscript]
 * @returns {Promise<{lessonPath: string, indexPath: string, readmePath: string,
 *   transcriptPath: string|null, entry: object}>}
 */
async function saveLesson({
  lesson,
  proposals = [],
  baseDir = process.cwd(),
  lessonDir = DEFAULT_LESSON_DIR,
  transcriptText = null,
  saveTranscript = false
} = {}) {
  if (!lesson?.source?.sourceKey) {
    throw new TypeError('saveLesson requires a lesson with a parsed source');
  }

  const directory = path.join(baseDir, lessonDir);
  await fs.mkdir(directory, { recursive: true });

  const lessonPath = path.join(directory, `${lesson.source.sourceKey}.md`);
  await fs.writeFile(lessonPath, renderLessonMarkdown(lesson, proposals), 'utf8');

  const indexPath = path.join(directory, 'index.json');
  const entry = buildIndexEntry(lesson, proposals);
  const entries = mergeIndex(await readJsonIfPresent(indexPath, []), entry);
  await fs.writeFile(indexPath, `${JSON.stringify(entries, null, 2)}\n`, 'utf8');

  const readmePath = path.join(directory, 'README.md');
  let readme;
  try {
    readme = await fs.readFile(readmePath, 'utf8');
  } catch {
    readme = '# Video Lessons\n';
  }
  await fs.writeFile(readmePath, applyIndexBlock(readme, renderIndexTable(entries)), 'utf8');

  // Regenerate the cross-lesson backlog, carrying over anything already ticked.
  const backlogPath = path.join(directory, BACKLOG_FILE);
  let existingBacklog = '';
  try {
    existingBacklog = await fs.readFile(backlogPath, 'utf8');
  } catch {
    existingBacklog = '';
  }
  await fs.writeFile(
    backlogPath,
    renderBacklog(entries, { checkedIds: parseCheckedIds(existingBacklog) }),
    'utf8'
  );

  let transcriptPath = null;
  if (saveTranscript && transcriptText) {
    const transcriptDir = path.join(directory, 'transcripts');
    await fs.mkdir(transcriptDir, { recursive: true });
    transcriptPath = path.join(transcriptDir, `${lesson.source.sourceKey}.txt`);
    await fs.writeFile(transcriptPath, `${transcriptText.trim()}\n`, 'utf8');
  }

  return { lessonPath, indexPath, readmePath, backlogPath, transcriptPath, entry };
}

module.exports = {
  renderLessonMarkdown,
  renderIndexTable,
  applyIndexBlock,
  buildIndexEntry,
  mergeIndex,
  saveLesson,
  lessonTitle,
  DEFAULT_LESSON_DIR,
  INDEX_START,
  INDEX_END
};
