'use strict';

// Caption-format parsers for the video learning connection.
//
// Split out from transcript-fetcher.js so the fiddly parsing logic is
// unit-testable without a network call or a yt-dlp binary. Every parser
// returns the same segment shape:
//   { start: <seconds>, duration: <seconds>, text: <string> }

const XML_ENTITIES = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&#39;': "'",
  '&apos;': "'",
  '&nbsp;': ' '
};

function decodeEntities(text) {
  if (typeof text !== 'string') return '';
  return text
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-f]+);/gi, (_, code) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&[a-z]+;|&#\d+;/gi, (entity) => XML_ENTITIES[entity.toLowerCase()] ?? entity);
}

function cleanSegmentText(text) {
  return decodeEntities(String(text || ''))
    // Caption karaoke markup and speaker-position tags.
    .replace(/<\/?[a-z][^>]*>/gi, '')
    // Auto-caption sound annotations that carry no instruction value.
    .replace(/\[(music|applause|laughter|inaudible|silence)\]/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Pull a top-level JSON object out of an HTML page by brace matching.
 * Regex cannot do this safely — YouTube's player response contains nested
 * objects and braces inside string literals.
 */
function extractJsonObject(html, marker) {
  if (typeof html !== 'string') return null;
  const markerIndex = html.indexOf(marker);
  if (markerIndex === -1) return null;
  const start = html.indexOf('{', markerIndex + marker.length);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = start; i < html.length; i += 1) {
    const char = html[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') inString = true;
    else if (char === '{') depth += 1;
    else if (char === '}') {
      depth -= 1;
      if (depth === 0) return html.slice(start, i + 1);
    }
  }
  return null;
}

/** Read the caption track list out of a YouTube watch page. */
function extractCaptionTracks(html) {
  const raw = extractJsonObject(html, 'ytInitialPlayerResponse');
  if (!raw) return [];
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return [];
  }
  const tracks =
    parsed?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(tracks)) return [];
  return tracks
    .filter((track) => track && typeof track.baseUrl === 'string')
    .map((track) => ({
      baseUrl: track.baseUrl,
      languageCode: track.languageCode || '',
      // YouTube marks machine-generated tracks with kind === 'asr'.
      autoGenerated: track.kind === 'asr',
      name: track.name?.simpleText || track.name?.runs?.[0]?.text || ''
    }));
}

/**
 * Choose the most useful caption track: human-written English first, then
 * auto-generated English, then any human-written track, then whatever exists.
 */
function pickCaptionTrack(tracks, preferredLanguage = 'en') {
  if (!Array.isArray(tracks) || tracks.length === 0) return null;
  const isPreferred = (track) =>
    track.languageCode.toLowerCase().startsWith(preferredLanguage.toLowerCase());
  return (
    tracks.find((track) => isPreferred(track) && !track.autoGenerated) ||
    tracks.find((track) => isPreferred(track)) ||
    tracks.find((track) => !track.autoGenerated) ||
    tracks[0]
  );
}

/** Parse YouTube's json3 caption format. */
function parseJson3(body) {
  let parsed;
  try {
    parsed = typeof body === 'string' ? JSON.parse(body) : body;
  } catch {
    return [];
  }
  const events = Array.isArray(parsed?.events) ? parsed.events : [];
  const segments = [];
  for (const event of events) {
    if (!Array.isArray(event?.segs)) continue;
    const text = cleanSegmentText(event.segs.map((seg) => seg?.utf8 || '').join(''));
    if (!text) continue;
    segments.push({
      start: Number(event.tStartMs || 0) / 1000,
      duration: Number(event.dDurationMs || 0) / 1000,
      text
    });
  }
  return segments;
}

/** Parse the legacy timedtext XML format. */
function parseTimedTextXml(body) {
  if (typeof body !== 'string') return [];
  const segments = [];
  const pattern = /<text\b([^>]*)>([\s\S]*?)<\/text>/gi;
  let match = pattern.exec(body);
  while (match !== null) {
    const attributes = match[1];
    const start = Number(/\bstart="([\d.]+)"/.exec(attributes)?.[1] || 0);
    const duration = Number(/\bdur="([\d.]+)"/.exec(attributes)?.[1] || 0);
    const text = cleanSegmentText(match[2]);
    if (text) segments.push({ start, duration, text });
    match = pattern.exec(body);
  }
  return segments;
}

function parseVttTimestamp(value) {
  // 00:01:02.500 or 01:02.500
  const match = /^(?:(\d+):)?(\d{1,2}):(\d{2})(?:[.,](\d{1,3}))?$/.exec(value.trim());
  if (!match) return null;
  const [, hours, minutes, seconds, millis] = match;
  return (
    Number(hours || 0) * 3600 +
    Number(minutes) * 60 +
    Number(seconds) +
    Number(millis || 0) / 1000
  );
}

/**
 * Parse WebVTT. YouTube's auto-generated VTT uses rolling captions where each
 * cue repeats the previous cue's tail, so identical and already-contained
 * lines are dropped to keep the transcript readable.
 */
function parseVtt(body) {
  if (typeof body !== 'string') return [];
  const segments = [];
  let previousText = '';

  for (const block of body.replace(/\r\n/g, '\n').split(/\n{2,}/)) {
    const lines = block.split('\n').map((line) => line.trim()).filter(Boolean);
    const cueIndex = lines.findIndex((line) => line.includes('-->'));
    if (cueIndex === -1) continue;

    const [rawStart, rawEnd] = lines[cueIndex].split('-->').map((part) => part.trim().split(/\s+/)[0]);
    const start = parseVttTimestamp(rawStart);
    const end = parseVttTimestamp(rawEnd);
    if (start === null) continue;

    const text = cleanSegmentText(lines.slice(cueIndex + 1).join(' '));
    if (!text) continue;
    if (text === previousText) continue;
    if (previousText && previousText.endsWith(text)) continue;

    // Rolling captions: keep only the newly revealed tail.
    let emitted = text;
    if (previousText && text.startsWith(previousText)) {
      emitted = text.slice(previousText.length).trim();
      if (!emitted) {
        previousText = text;
        continue;
      }
    }

    segments.push({
      start,
      duration: end !== null ? Math.max(0, end - start) : 0,
      text: emitted
    });
    previousText = text;
  }
  return segments;
}

/** Dispatch to the right parser based on a subtitle filename. */
function parseSubtitleFile(filename, body) {
  const lower = String(filename || '').toLowerCase();
  if (lower.endsWith('.json3') || lower.endsWith('.json')) return parseJson3(body);
  if (lower.endsWith('.vtt')) return parseVtt(body);
  if (lower.endsWith('.xml') || lower.endsWith('.srv1')) return parseTimedTextXml(body);
  // Unknown extension: sniff the content instead of giving up.
  const trimmed = String(body || '').trimStart();
  if (trimmed.startsWith('{')) return parseJson3(body);
  if (trimmed.startsWith('WEBVTT')) return parseVtt(body);
  if (trimmed.startsWith('<')) return parseTimedTextXml(body);
  return [];
}

/**
 * Turn free-form pasted text into segments. Used for the manual path, where
 * the owner supplies a transcript by hand and there are no timings.
 * Lines prefixed with a timestamp ("1:23 something") keep that offset.
 */
function parsePlainTranscript(body) {
  if (typeof body !== 'string') return [];
  const segments = [];
  for (const line of body.replace(/\r\n/g, '\n').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const stamped = /^\[?(\d{1,2}:\d{2}(?::\d{2})?)\]?\s*[-–—:]?\s*(.+)$/.exec(trimmed);
    if (stamped) {
      const parts = stamped[1].split(':').map(Number);
      const start =
        parts.length === 3
          ? parts[0] * 3600 + parts[1] * 60 + parts[2]
          : parts[0] * 60 + parts[1];
      const text = cleanSegmentText(stamped[2]);
      if (text) segments.push({ start, duration: 0, text });
      continue;
    }
    const text = cleanSegmentText(trimmed);
    if (text) segments.push({ start: null, duration: 0, text });
  }
  return segments;
}

/** Join segments into a single readable transcript string. */
function segmentsToText(segments) {
  if (!Array.isArray(segments)) return '';
  return segments
    .map((segment) => segment.text)
    .filter(Boolean)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
}

module.exports = {
  extractJsonObject,
  extractCaptionTracks,
  pickCaptionTrack,
  parseJson3,
  parseTimedTextXml,
  parseVtt,
  parseSubtitleFile,
  parsePlainTranscript,
  segmentsToText,
  cleanSegmentText,
  decodeEntities
};
