'use strict';

// Transcript acquisition for the video learning connection.
//
// Four strategies, tried in order of fidelity-per-cost. Every one of them can
// legitimately be unavailable in a given environment, so the module reports
// what it tried and why each attempt failed instead of throwing:
//
//   1. manual        — transcript text supplied by the owner. Always available,
//                      and the only path that works for most Instagram media.
//   2. yt-dlp        — real caption tracks (and Instagram support) when the
//                      binary is installed. Best automatic option.
//   3. youtube-page  — scrape the watch page's caption track list. No extra
//                      dependency, YouTube only, breaks if YouTube changes
//                      its player payload.
//   4. whisper       — download the audio with yt-dlp and transcribe it with
//                      OpenAI. The only path that works when a video has no
//                      captions at all. Needs yt-dlp, ffmpeg, and an API key.
//
// A caller that gets status 'needs_manual' has NOT been given a transcript —
// it must not proceed as if it had one. This is deliberately fail-closed:
// inventing lesson content from a title is exactly the "reported success on a
// proxy for the result" failure the working agreement forbids.

const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');

const {
  extractCaptionTracks,
  pickCaptionTrack,
  parseJson3,
  parseTimedTextXml,
  parseSubtitleFile,
  parsePlainTranscript,
  segmentsToText
} = require('./transcript-parsers');

const execFileAsync = promisify(execFile);

// A desktop UA keeps YouTube from serving the stripped-down mobile page that
// omits the caption track list.
const BROWSER_USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const DEFAULT_HTTP_TIMEOUT_MS = 30000;
const DEFAULT_YTDLP_TIMEOUT_MS = 180000;
// OpenAI's audio transcription endpoint rejects uploads over 25 MB.
const WHISPER_MAX_BYTES = 25 * 1024 * 1024;

async function fetchText(url, { timeoutMs = DEFAULT_HTTP_TIMEOUT_MS, headers = {} } = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(url, {
      signal: controller.signal,
      headers: {
        'User-Agent': BROWSER_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9',
        ...headers
      }
    });
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    return await response.text();
  } finally {
    clearTimeout(timer);
  }
}

/** Is a binary callable on this machine? */
async function hasBinary(binary) {
  try {
    await execFileAsync(binary, ['--version'], { timeout: 15000 });
    return true;
  } catch {
    return false;
  }
}

function describeError(error) {
  if (!error) return 'unknown error';
  // yt-dlp writes the useful part of a failure to stderr.
  const stderr = typeof error.stderr === 'string' ? error.stderr.trim() : '';
  if (stderr) return stderr.split('\n').slice(-2).join(' ').slice(0, 300);
  return String(error.message || error).slice(0, 300);
}

// ---------------------------------------------------------------------------
// Strategy 1: manual transcript
// ---------------------------------------------------------------------------

function buildManualTranscript(text) {
  const segments = parsePlainTranscript(text);
  if (segments.length === 0) return null;
  return {
    segments,
    text: segmentsToText(segments),
    language: 'unknown',
    autoGenerated: false
  };
}

// ---------------------------------------------------------------------------
// Strategy 2: yt-dlp caption tracks
// ---------------------------------------------------------------------------

async function ytDlpMetadata(url, { timeoutMs = DEFAULT_YTDLP_TIMEOUT_MS } = {}) {
  const { stdout } = await execFileAsync(
    'yt-dlp',
    ['--skip-download', '--no-warnings', '--dump-single-json', url],
    { timeout: timeoutMs, maxBuffer: 32 * 1024 * 1024 }
  );
  const parsed = JSON.parse(stdout);
  return {
    title: parsed.title || null,
    author: parsed.uploader || parsed.channel || parsed.uploader_id || null,
    durationSeconds: Number.isFinite(parsed.duration) ? parsed.duration : null,
    description: parsed.description || null,
    uploadDate: parsed.upload_date || null,
    viewCount: Number.isFinite(parsed.view_count) ? parsed.view_count : null
  };
}

async function ytDlpSubtitles(url, { timeoutMs = DEFAULT_YTDLP_TIMEOUT_MS, language = 'en' } = {}) {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'video-learning-subs-'));
  try {
    await execFileAsync(
      'yt-dlp',
      [
        '--skip-download',
        '--no-warnings',
        '--write-subs',
        '--write-auto-subs',
        '--sub-langs',
        `${language}.*,${language},-live_chat`,
        '--sub-format',
        'json3/vtt/best',
        '-o',
        path.join(workDir, 'captions.%(ext)s'),
        url
      ],
      { timeout: timeoutMs, maxBuffer: 32 * 1024 * 1024 }
    );

    const files = await fs.readdir(workDir);
    // Prefer json3 (clean, one cue per line) over vtt (rolling duplicates).
    // yt-dlp only marks some auto-caption files in the filename, so the
    // autoGenerated flag here is a hint for ranking, not a guarantee.
    const ranked = files
      .map((file) => ({
        file,
        autoGenerated: /\.(auto|orig)\b/i.test(file),
        json: file.toLowerCase().endsWith('.json3') || file.toLowerCase().endsWith('.json')
      }))
      .sort((a, b) => Number(a.autoGenerated) - Number(b.autoGenerated) || Number(b.json) - Number(a.json));

    for (const candidate of ranked) {
      const body = await fs.readFile(path.join(workDir, candidate.file), 'utf8');
      const segments = parseSubtitleFile(candidate.file, body);
      if (segments.length > 0) {
        return {
          segments,
          text: segmentsToText(segments),
          language,
          autoGenerated: candidate.autoGenerated
        };
      }
    }
    return null;
  } finally {
    await fs.rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

// ---------------------------------------------------------------------------
// Strategy 3: YouTube watch-page caption tracks
// ---------------------------------------------------------------------------

async function fetchYouTubePage(source, { timeoutMs = DEFAULT_HTTP_TIMEOUT_MS } = {}) {
  return fetchText(source.canonicalUrl, {
    timeoutMs,
    // Skips the EU consent interstitial, which otherwise replaces the player payload.
    headers: { Cookie: 'CONSENT=YES+cb; SOCS=CAI' }
  });
}

async function fetchYouTubePageTranscript(source, { timeoutMs = DEFAULT_HTTP_TIMEOUT_MS, html } = {}) {
  const page = html ?? (await fetchYouTubePage(source, { timeoutMs }));

  const tracks = extractCaptionTracks(page);
  if (tracks.length === 0) return null;

  const track = pickCaptionTrack(tracks);
  if (!track) return null;

  const jsonUrl = `${track.baseUrl}${track.baseUrl.includes('?') ? '&' : '?'}fmt=json3`;
  const body = await fetchText(jsonUrl, { timeoutMs });
  let segments = parseJson3(body);
  if (segments.length === 0) {
    // Older tracks still answer in the legacy XML format.
    segments = parseTimedTextXml(await fetchText(track.baseUrl, { timeoutMs }));
  }
  if (segments.length === 0) return null;

  return {
    segments,
    text: segmentsToText(segments),
    language: track.languageCode || 'unknown',
    autoGenerated: track.autoGenerated
  };
}

function extractPageMetadata(html) {
  const meta = (property) => {
    const pattern = new RegExp(
      `<meta[^>]+(?:property|name)=["']${property}["'][^>]*content=["']([^"']*)["']`,
      'i'
    );
    const alternate = new RegExp(
      `<meta[^>]+content=["']([^"']*)["'][^>]*(?:property|name)=["']${property}["']`,
      'i'
    );
    return pattern.exec(html)?.[1] || alternate.exec(html)?.[1] || null;
  };
  const duration = meta('video:duration') || meta('og:video:duration');
  return {
    title: meta('og:title') || /<title>([^<]*)<\/title>/i.exec(html)?.[1] || null,
    author: meta('author') || meta('og:video:tag') || null,
    durationSeconds: duration ? Number(duration) : null,
    description: meta('og:description') || meta('description') || null
  };
}

// ---------------------------------------------------------------------------
// Strategy 4: audio download + OpenAI transcription
// ---------------------------------------------------------------------------

function resolveWhisperConfig(env = process.env) {
  const apiKey = (env.AI_API_KEY || env.OPENAI_API_KEY || '').trim();
  return {
    apiKey,
    model: (env.VIDEO_TRANSCRIBE_MODEL || 'whisper-1').trim(),
    enabled: apiKey.length > 0
  };
}

async function transcribeAudioFile(filePath, config) {
  const stats = await fs.stat(filePath);
  if (stats.size > WHISPER_MAX_BYTES) {
    throw new Error(
      `audio is ${(stats.size / 1024 / 1024).toFixed(1)} MB, over the ${WHISPER_MAX_BYTES / 1024 / 1024} MB transcription limit`
    );
  }

  const form = new FormData();
  form.append('file', new Blob([await fs.readFile(filePath)]), path.basename(filePath));
  form.append('model', config.model);
  form.append('response_format', 'verbose_json');

  const response = await fetch('https://api.openai.com/v1/audio/transcriptions', {
    method: 'POST',
    headers: { Authorization: `Bearer ${config.apiKey}` },
    body: form
  });
  if (!response.ok) {
    throw new Error(`transcription API returned HTTP ${response.status}`);
  }

  const parsed = await response.json();
  const segments = Array.isArray(parsed.segments)
    ? parsed.segments
        .map((segment) => ({
          start: Number(segment.start || 0),
          duration: Math.max(0, Number(segment.end || 0) - Number(segment.start || 0)),
          text: String(segment.text || '').trim()
        }))
        .filter((segment) => segment.text)
    : [];

  const text = segments.length > 0 ? segmentsToText(segments) : String(parsed.text || '').trim();
  if (!text) return null;
  return {
    segments: segments.length > 0 ? segments : [{ start: 0, duration: 0, text }],
    text,
    language: parsed.language || 'unknown',
    autoGenerated: true
  };
}

async function transcribeWithWhisper(url, { config, timeoutMs = DEFAULT_YTDLP_TIMEOUT_MS } = {}) {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'video-learning-audio-'));
  try {
    await execFileAsync(
      'yt-dlp',
      [
        '--no-warnings',
        '-f',
        'bestaudio/best',
        '-x',
        '--audio-format',
        'mp3',
        // Speech only needs a fraction of music bitrate, and staying small
        // keeps long videos under the upload limit.
        '--audio-quality',
        '9',
        '-o',
        path.join(workDir, 'audio.%(ext)s'),
        url
      ],
      { timeout: timeoutMs, maxBuffer: 32 * 1024 * 1024 }
    );
    const files = await fs.readdir(workDir);
    const audioFile = files.find((file) => /\.(mp3|m4a|webm|ogg|wav)$/i.test(file));
    if (!audioFile) throw new Error('yt-dlp produced no audio file');
    return await transcribeAudioFile(path.join(workDir, audioFile), config);
  } finally {
    await fs.rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

// ---------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------

function guidanceFor(platform) {
  if (platform === 'instagram') {
    return (
      'Instagram does not expose captions to unauthenticated clients. Install ' +
      'yt-dlp for public reels, or re-run with --transcript-file pointing at ' +
      'the caption/voiceover text.'
    );
  }
  return (
    'Install yt-dlp (and ffmpeg plus AI_API_KEY for audio transcription of ' +
    'caption-less videos), or re-run with --transcript-file.'
  );
}

/**
 * Acquire a transcript for a parsed video source.
 *
 * @param {object} input
 * @param {object} input.source - a source from parseVideoUrl()
 * @param {string} [input.manualTranscript] - owner-supplied transcript text
 * @param {object} [input.env] - environment used for API key lookup
 * @param {boolean} [input.allowWhisper] - permit the paid audio path
 * @returns {Promise<{status: 'ok'|'needs_manual', strategy: string|null,
 *   transcript: object|null, metadata: object, attempts: Array}>}
 */
async function fetchTranscript({
  source,
  manualTranscript = null,
  env = process.env,
  allowWhisper = true
} = {}) {
  if (!source || !source.canonicalUrl) {
    throw new TypeError('fetchTranscript requires a parsed video source');
  }

  const attempts = [];
  let metadata = { title: null, author: null, durationSeconds: null, description: null };

  const record = (strategy, ok, detail) => attempts.push({ strategy, ok, detail });

  // 1. Manual transcript wins outright — the owner already did the work.
  if (typeof manualTranscript === 'string' && manualTranscript.trim()) {
    const transcript = buildManualTranscript(manualTranscript);
    if (transcript) {
      record('manual', true, `${transcript.segments.length} supplied lines`);
      return { status: 'ok', strategy: 'manual', transcript, metadata, attempts };
    }
    record('manual', false, 'supplied transcript contained no usable text');
  }

  const ytDlpAvailable = await hasBinary('yt-dlp');

  // Metadata is best-effort: a lesson is still useful without a title.
  if (ytDlpAvailable) {
    try {
      metadata = { ...metadata, ...(await ytDlpMetadata(source.canonicalUrl)) };
    } catch (error) {
      record('yt-dlp-metadata', false, describeError(error));
    }
  }

  // 2. yt-dlp caption tracks.
  if (ytDlpAvailable) {
    try {
      const transcript = await ytDlpSubtitles(source.canonicalUrl);
      if (transcript) {
        record('yt-dlp', true, `${transcript.segments.length} caption lines`);
        return { status: 'ok', strategy: 'yt-dlp', transcript, metadata, attempts };
      }
      record('yt-dlp', false, 'no caption track available for this video');
    } catch (error) {
      record('yt-dlp', false, describeError(error));
    }
  } else {
    record('yt-dlp', false, 'yt-dlp is not installed');
  }

  // 3. YouTube watch-page scrape.
  if (source.platform === 'youtube') {
    try {
      // Fetched once and reused: the page carries both the metadata and the
      // caption track list.
      const html = await fetchYouTubePage(source);
      // yt-dlp's metadata is richer, so anything it already found wins.
      metadata = { ...extractPageMetadata(html), ...stripNulls(metadata) };
      const transcript = await fetchYouTubePageTranscript(source, { html });
      if (transcript) {
        record('youtube-page', true, `${transcript.segments.length} caption lines`);
        return { status: 'ok', strategy: 'youtube-page', transcript, metadata, attempts };
      }
      record('youtube-page', false, 'watch page exposed no caption track');
    } catch (error) {
      record('youtube-page', false, describeError(error));
    }
  }

  // 4. Audio transcription.
  const whisperConfig = resolveWhisperConfig(env);
  if (!allowWhisper) {
    record('whisper', false, 'audio transcription disabled for this run');
  } else if (!ytDlpAvailable) {
    record('whisper', false, 'needs yt-dlp to download the audio');
  } else if (!whisperConfig.enabled) {
    record('whisper', false, 'no AI_API_KEY/OPENAI_API_KEY set');
  } else if (!(await hasBinary('ffmpeg'))) {
    record('whisper', false, 'ffmpeg is not installed');
  } else {
    try {
      const transcript = await transcribeWithWhisper(source.canonicalUrl, { config: whisperConfig });
      if (transcript) {
        record('whisper', true, `${transcript.segments.length} transcribed segments`);
        return { status: 'ok', strategy: 'whisper', transcript, metadata, attempts };
      }
      record('whisper', false, 'transcription returned no text');
    } catch (error) {
      record('whisper', false, describeError(error));
    }
  }

  return {
    status: 'needs_manual',
    strategy: null,
    transcript: null,
    metadata,
    attempts,
    guidance: guidanceFor(source.platform)
  };
}

function stripNulls(object) {
  return Object.fromEntries(Object.entries(object).filter(([, value]) => value !== null && value !== undefined));
}

module.exports = {
  fetchTranscript,
  buildManualTranscript,
  extractPageMetadata,
  resolveWhisperConfig,
  hasBinary,
  WHISPER_MAX_BYTES
};
